### ISSUE TITLE
Add link and keywords to About section

### ISSUE THREAD

**Issue by J535D165** [hugoquene/QMS-EN#6]
It would be nice to have the link to the gitbook https://hugoquene.github.io/QMS-EN/ added to the **About** section of the repo. This makes it easier findable via Github. 

Keywords would also be nice to have. Don't forget to add https://github.com/topics/utrecht-university.

**Comment by hugoquene** [comment]
Dear J, thanks for raising this issue, great suggestions. I've added a link to the gitbook itself and added keywords on the About page. Likewise updated the parallel Dutch version (!) at https://hugoquene.github.io/KMS-NL. I'll close the issue for now - thanks! H
